# Spring profile
spring.profiles.active=dev

# Spring server

# Allow "|" character in the URL
server.tomcat.relaxed-query-chars=|

# Log
logging.level.root=INFO

# ===============================
# Redis Configuration
# ===============================
spring.cache.type=redis

spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password= (descomentar se usar senha)
# spring.redis.database=0 (opcional, default é 0)

# Tempo de vida padrão dos caches em milissegundos (30 dias)
spring.cache.redis.time-to-live=2592000000

ocl.base-url=${OCL_BASE_URL:https://oclapi2.ips.hsl.org.br}

server.port=443
server.address=0.0.0.0
server.ssl.enabled=true
server.ssl.key-store=classpath:tls/terminology.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-alias=terminology
